[package]
name = "bottt"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shuttle-runtime = "0.16.0"
anyhow = "1.0.71"
poise = "0.5.5"
shuttle-poise = "0.16.0"
shuttle-secrets = "0.16.0"
tokio = "1.28.1"
tracing = "0.1.37"
# songbird = { version = "0.3.2", features = ["yt-dlp"] }
songbird = "0.3.2"
url = "2.2.2"
shuttle-static-folder = "0.16.0"
chrono = "0.4.19"
serenity = { version = "0.11.5", default-features = false }
